spring.application.name=ai-interview-preparation-platform
server.port=${PORT:8080}
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
server.servlet.session.timeout=60m
